name: List environment variables
description: List all environment variables
runs:
  using: composite
  steps:
    - name: List environment variables
      run: env
      shell: bash

    - name: Echo ${{ github.action_repository }}
      run: echo "github.action_repository = ${{ github.action_repository }}"
      shell: bash
